import jsPDF from 'jspdf';
import { Download } from 'lucide-react';

interface StrategyExportButtonProps {
  modelName: string;
  infraName: string;
  dbName: string;
  requests: number;
  growth: number;
  monthlyTotal: number;
  tco: number;
}

export function StrategyExportButton(props: StrategyExportButtonProps) {
  const handleExport = () => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(0, 122, 255); // Accent Blue
    doc.text("Cloud Strategy Pricing Report", 20, 20);
    
    doc.setFontSize(14);
    doc.setTextColor(30, 30, 30);
    doc.text("Project: CFO Bot - Almaty RE Price Predictor", 20, 35);

    doc.setFontSize(12);
    doc.text(`ML Inference Engine: ${props.modelName}`, 20, 50);
    doc.text(`Infrastructure Tier: ${props.infraName}`, 20, 60);
    doc.text(`Database Tier: ${props.dbName}`, 20, 70);
    
    doc.text(`Monthly Requests: ${props.requests.toLocaleString()}`, 20, 90);
    doc.text(`Monthly Data Growth (g): ${props.growth}%`, 20, 100);

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text(`Projected Monthly Cost (C_mo): $${props.monthlyTotal.toFixed(2)}`, 20, 120);
    doc.text(`12-Month TCO: $${props.tco.toFixed(2)}`, 20, 130);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by Google Antigravity Agent SDD Workflow.", 20, 280);

    doc.save("Cloud-Strategy-Report.pdf");
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center justify-center gap-2 w-full mt-6 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold py-4 px-6 rounded-xl transition duration-300 shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:shadow-[0_0_30px_rgba(6,182,212,0.5)] transform hover:-translate-y-0.5"
    >
      <Download size={20} />
      <span>Calculate Estimate</span>
    </button>
  );
}
